In [1]:
# Find number of athletes meeting 84th singapore open threshold marks

#1. At least 1 athlete per event per gender
#2. Except for 100m, 400m, cap at 3 athletes per event. 100m, 400m capped at 6
#3. Where top athlete is >30 yrs old (except marathon), to include next athlete as well (below 30)
#4. Where althlete qualified in 2 events, to choose the better performing one
#5. For athletes looking to do full time, to write in to SAA for special consideration
#6. Exclude SPEX carded athletes
#7. Except for marathon, age threshold cut off of 40 yrs old for top athlete
#8. No double tapping of prog - potential names in red


%load_ext autoreload
%autoreload 2

In [2]:
# Import usual modules
import pandas as pd
import csv
import math
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import openpyxl
import datetime
from scipy.stats import lognorm
import re
import string
from bs4 import BeautifulSoup
import requests
import unicodedata # for removing accented characters
import datetime
import icecream as ic
import dateutil.parser as parser 
import streamlit as st
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.express as px
from plotly.subplots import make_subplots


from google.cloud import storage

In [3]:
# PRODUCTION ENVIRONMENT
# Extract timed event records

import pandas_gbq
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
    
    
)

sql1="""
SELECT NAME, RESULT, TEAM, AGE, RANK AS COMPETITION_RANK, DIVISION, EVENT, DISTANCE, EVENT_CLASS, UNIQUE_ID, DOB, NATIONALITY, WIND, CATEGORY_EVENT, GENDER, COMPETITION, YEAR, REGION
FROM `saa-analytics.results.athlete_results_prod` 
WHERE RESULT!='NM' AND RESULT!='-' AND RESULT!='DNS' AND RESULT!='DNF' AND RESULT!='DNQ' AND RESULT!='DQ' AND RESULT IS NOT NULL

"""


competitors = pandas_gbq.read_gbq(sql1, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [4]:
competitors

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,YEAR,REGION
0,Shanti Veronica Pereira,11.71,nan,nan,7.0,nan,100m,nan,nan,nan,20-Sep-96,SGP,-1.8,Sprint,Female,AtleticaGenève,2025,International
1,Shanti Veronica Pereira,23.16w,nan,nan,7.0,nan,200m,nan,nan,nan,20-Sep-96,SGP,2.4,Sprint,Female,AtleticaGenève,2025,International
2,Jun Yu Low,4.77,nan,nan,5.0,nan,Pole Vault,nan,nan,nan,21-Apr-01,SGP,nan,Jump,Male,Jan Dietvorst Memorial,2025,International
3,Tung Hon Andrew Pak,2.05,nan,nan,nan,nan,High Jump,nan,nan,nan,10-Apr-02,SGP,nan,Jump,Male,National Championships,2025,International
4,Tam Jong Hng,1.95,nan,nan,nan,nan,High Jump,nan,nan,nan,nan,SGP,nan,Jump,Male,National Championships,2025,International
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31169,Charlene Lee,8.90,NYGH,None,15,C,Triple Jump,None,None,None,None,None,None,Jump,Female,National School Games,2024,Local
31170,"Ng Jing Wen, Ariel",10.33,RGS,None,2,C,Triple Jump,None,None,None,None,None,None,Jump,Female,National School Games,2024,Local
31171,LEE GABRIEL JIN YI,14.5,SINGAPORE,21,3,None,Triple jump,None,None,None,2003,SGP,NWI,Jump,Male,Victor Saneev Memorial (Georgia),2024,International
31172,"SYED AHMED RIADH, SHARIFAH FALISHA",11.13,SINGAPORE SPORTS SCHOOL,18,None,None,Triple jump,None,None,None,2006,SGP,NWI,Jump,Female,FTKLAA State Meet,2024,International
31173,GOH YEN YOUNG AMELIA,10.73,SINGAPORE,16,2,U18,Triple jump,None,None,None,2008,SGP,2.3,Jump,Female,Hong Kong Inter-City,2024,International

In [5]:
# Remove special characters before mapping

athletes = competitors

for col in athletes.columns:
    athletes[col] = athletes[col].astype(str)
    athletes[col] = athletes[col].str.replace('\xa0', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('[\x00-\x1f\x7f-\x9f]', '', regex=True)
    athletes[col] = athletes[col].str.replace('\r', ' ', regex=True)
    athletes[col] = athletes[col].str.replace('\n', ' ', regex=True)
    athletes[col] = athletes[col].str.strip()

# Create temporary mapped event column

athletes['MAPPED_EVENT']=''

# Correct javelin category

mask = athletes['EVENT'].str.contains(r'Javelin', na=True)
athletes.loc[mask, 'CATEGORY_EVENT'] = 'Throw'

# Throws



#mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'600g', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw|Javelin', na=False) & athletes['EVENT_CLASS'].str.contains(r'800g', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
#mask = (athletes['EVENT'].str.contains(r'Javelin Throw|Javelin throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'
mask = (athletes['EVENT'].str.contains(r'Javelin|Javelin Throw', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Javelin Throw'



#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False, regex=True) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS']=='4kg'))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Male') & (athletes['EVENT_CLASS'].str.contains(r'7.26', na=False)))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'
#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['GENDER']=='Female') & (athletes['EVENT_CLASS'].str.contains(r'4', na=False)))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

#mask = (athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'

mask = athletes['EVENT'].str.contains(r'Shot Put|Shot put', na=False)# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Shot Put'



#mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'7.26kg', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
#mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'4.00kg', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
mask = (athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) & (athletes['DIVISION'].str.contains(r'OPEN|Open', na=False)))# there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'
ask = athletes['EVENT'].str.contains(r'Hammer Throw|Hammer throw', na=False) # there are some additional characters after Put
athletes.loc[mask, 'MAPPED_EVENT'] = 'Hammer Throw'



#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = ((athletes['EVENT'].str.contains(r'Discus\s\(1\.00kg\)', na=False))  & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


mask = athletes['EVENT'].str.contains(r'Discus\sThrow', na=False)
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
#mask = ((athletes['EVENT'].str.contains(r'Discus\sThrow\s\(1kg\)', na=False)) & (athletes['GENDER']=='Female'))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'2kg|2.00kg', na=False) & athletes['GENDER'].str.contains(r'Male', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus|Discus throw', na=False) & athletes['EVENT_CLASS'].str.contains(r'1kg|1.00kg', na=False) & athletes['GENDER'].str.contains(r'Female', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

#mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['REGION'].str.contains(r'International', na=False))
#athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'OPEN|Open', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'
mask = (athletes['EVENT'].str.contains(r'Discus Throw|Discus throw', na=False) & athletes['DIVISION'].str.contains(r'None', na=False) & athletes['EVENT_CLASS'].str.contains(r'None', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'

mask = (athletes['EVENT'].str.contains(r'Discus', na=False))
athletes.loc[mask, 'MAPPED_EVENT'] = 'Discus Throw'


mask = (athletes['DIVISION'].str.contains(r'A', na=False))
athletes.loc[mask, 'AGE'] = '18.5'

mask = (athletes['DIVISION'].str.contains(r'B', na=False))
athletes.loc[mask, 'AGE'] = '16'

mask = (athletes['DIVISION'].str.contains(r'C', na=False))
athletes.loc[mask, 'AGE'] = '13.5'

In [6]:
athletes = athletes[athletes['CATEGORY_EVENT']=='Throw']

In [7]:
# Exclude foreigners from MALAYSIA, THAILAND etc.

df_selected = athletes[(athletes['TEAM']!='Malaysia')&(athletes['TEAM']!='THAILAND')&(athletes['TEAM']!='China') 
                       &(athletes['TEAM']!='South Korea')&(athletes['TEAM']!='Laos') 
                       &(athletes['TEAM']!='Philippines')&(athletes['TEAM']!='Piboonbumpen Thailand') 
                       &(athletes['TEAM']!='Chinese Taipei')&(athletes['TEAM']!='Gurkha Contingent') 
                       &(athletes['TEAM']!='Australia')&(athletes['TEAM']!='Piboonbumpen Thailand') 
                       &(athletes['TEAM']!='Hong Kong')&(athletes['TEAM']!='PERAK')&(athletes['TEAM']!='Sri Lanka') 
                       &(athletes['TEAM']!='Indonesia')&(athletes['TEAM']!='THAILAND')&(athletes['TEAM']!='MALAYSIA') 
                       &(athletes['TEAM']!='PHILIPPINES') & (athletes['TEAM']!='SOUTH KOREA')&(athletes['TEAM']!='Waseda') 
                       &(athletes['TEAM']!='LAOS')&(athletes['TEAM']!='CHINESE TAIPEI')
                       &(athletes['TEAM']!='INDIA')&(athletes['TEAM']!='Hong Kong, China')&(athletes['TEAM']!='AIC JAPAN')]

In [8]:
df_selected = df_selected[df_selected['DIVISION']!='Masters']

In [9]:
df_selected.reset_index(inplace=True, drop=True)

In [10]:
df_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,YEAR,REGION,MAPPED_EVENT
0,"Chong Bin Mohd Isham, Akid",32.40m,FAC,34,2,Open,Hammer Throw,0,(7.26kg),A512E90,24/11/90,nan,,Throw,Male,54th SA Inter Club Championships 2024,2024,Local,Hammer Throw
1,"Ng, Joash",1.89m,Team M&J,5,10,U7,Shot Put,0,1kg Medicine,nan,11/1/19,nan,,Throw,Male,11th Club ZOOM Kindred Spirit 2024 & PEERS,2024,Local,Shot Put
2,"Franz, Alexander",3.43m,Club ZOOM,5,3,U7,Shot Put,0,1kg Medicine,nan,26/4/19,nan,,Throw,Male,11th Club ZOOM Kindred Spirit 2024 & PEERS,2024,Local,Shot Put
3,"Lee, Tzu Yun",53.18m,Club Zoom,30,1,Open,Discus Throw,0,,nan,24/11/94,nan,,Throw,Male,84th Singapore Open Track & Field,2024,Local,Discus Throw
4,"YEE WAI TENG, MELISSA",10.60m,SINGAPORE,26,2,Open,Shot Put,0,,nan,8/8/98,nan,,Throw,Female,84th Singapore Open Track & Field,2024,Local,Shot Put
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,"Sheik Alau'ddin, Sheik Fayz",9.40m,Republic Polytechnic,0,3,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put
1704,"Tay, Arvin",10.07m,Singapore Management Universit,0,2,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put
1705,"Josiah, Chan",7.03m,Singapore Polytechnic,0,7,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put
1706,"Subba, Sugam",7.17m,Singapore Polytechnic,0,6,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put
1707,Raeshon Loo Wei Ming,12.01,None,None,3,None,Shot Put,None,None,None,31-Jan-01,SGP,None,Throw,Male,Teivashüppe GP Lasnamäe KJH,2025,International,Shot Put

In [11]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')


df_selected.to_csv('athletes_throws_mapped.csv', sep=',', encoding='utf-8-sig', index=False)

In [12]:
# Converts any time format into seconds

def convert_time(i, string, metric):

    global output
    
    l=['discus', 'throw', 'jump', 'vault', 'shot']
        
    string=string.lower()
    
   # print('metric', metric)
    
    try:
        
        if 'w' in metric:  # skip marks with illegal wind speeds
            
            print('W', metric)
            
            output=''
            
        else:
            
    
            if any(s in string for s in l)==True:
            
                if 'm' in metric:
            
                    metric=metric.replace('m', '')
                    output=float(str(metric))
            
                elif 'GR' in metric:
            
                    metric=metric.replace('GR', '')
                    output=float(str(metric))
                
          #  elif 'w' in metric:
                
               
           #     metric1=metric.replace('w', '')
                
           #     output=float(str(metric1))
                
                else:
    
                    output=float(str(metric))
        
        #elif 'w' in metric:
            
                
         #       metric1=metric.replace('w', '')
                             
         #       output=float(str(metric1))
                
                
        
            else:
        
                searchstring = ":"
                searchstring2 = "."
                substring=str(metric)
                count = substring.count(searchstring)
                count2 = substring.count(searchstring2)
            
                if count==0:
                
                    output=float(substring)
            
            
      #      elif 'marathon' in string and count==2:
                
      #          print('HERE', metric)
                
      #          metric = metric.replace(":", ".", 2)
                
      #          print('METRIC', metric)
                
       #         h,m,s = metric.split(':')            

       #         output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())

               
             
                elif (type(metric)==datetime.time or type(metric)==datetime.datetime):
                
                                                
                    time=str(metric)
                    h, m ,s = time.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
            
                                
                elif (count==1 and count2==1):
            
                    m,s = metric.split(':')
                    output = float(datetime.timedelta(minutes=int(m),seconds=float(s)).total_seconds())
                     
                elif (count==1 and count2==2):
                
            
                    metric = metric.replace(".", ":", 1)
            
                    h,m,s = metric.split(':')            
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
                
        
                elif (count==2 and count2==0):
                
            
                    h,m,s = metric.split(':')
                    output = float(datetime.timedelta(hours=int(h),minutes=int(m),seconds=float(s)).total_seconds())
  
            

    except:
        
        pass
                
    return output

In [13]:
for i in range(len(df_selected)):
        
    rowIndex = df_selected.index[i]

    input_string=df_selected.iloc[rowIndex,18]
    
    metric=df_selected.iloc[rowIndex,1]
    
    if metric==None:
        continue
        
    out = convert_time(i, input_string, metric)
    
    print(rowIndex, input_string, out)
     
    df_selected.loc[rowIndex, 'Metric'] = out

0 Hammer Throw 32.4
1 Shot Put 1.89
2 Shot Put 3.43
3 Discus Throw 53.18
4 Shot Put 10.6
5 Discus Throw 35.41
6 Shot Put 11.44
7 Shot Put 11.03
8 Discus Throw 37.84
9 Javelin Throw 43.78
10 Shot Put 11.63
11 Javelin Throw 32.4
12 Discus Throw 25.5
13 Shot Put 8.39
14 Shot Put 7.4
15 Javelin Throw 27.17
16 Discus Throw 15.6
17 Shot Put 6.15
18 Shot Put 10.86
19 Shot Put 10.58
20 Shot Put 7.91
21 Javelin Throw 52.9
22 Discus Throw 35.22
23 Shot Put 9.82
24 Discus Throw 32.28
25 Shot Put 11.28
26 Javelin Throw 56.64
27 Javelin Throw 54.1
28 Javelin Throw 29.75
29 Shot Put 10.64
30 Hammer Throw 32.19
31 Javelin Throw 53.81
32 Discus Throw 31.39
33 Javelin Throw 61.54
34 Discus Throw 37.13
35 Shot Put 37.13
36 Javelin Throw 30.06
37 Javelin Throw 22.89
38 Shot Put 11.58
39 Discus Throw 30.48
40 Javelin Throw 26.18
41 Javelin Throw 24.25
42 Hammer Throw 21.33
43 Discus Throw 25.51
44 Javelin Throw 25.59
45 Javelin Throw 37.96
46 Javelin Throw 33.67
47 Hammer Throw 12.81
48 Discus Throw 13.64
49 Shot Put 12.13
50 Shot Put 8.68
51 Shot Put 11.36
52 Discus Throw 59.42
53 Discus Throw 45.93
54 Shot Put 17.2
55 Shot Put 8.9
56 Javelin Throw 22.16
57 Javelin Throw 23.59
58 Javelin Throw 21.38
59 Discus Throw 20.2
60 Discus Throw 17.91
61 Discus Throw 17.82
62 Shot Put 8.53
63 Shot Put 10.8
64 Shot Put 9.1
65 Javelin Throw 23.12
66 Javelin Throw 18.57
67 Javelin Throw 25.64
68 Discus Throw 25.6
69 Discus Throw 28.43
70 Discus Throw 25.85
71 Shot Put 7.14
72 Shot Put 8.53
73 Shot Put 8.36
74 Shot Put 9.89
75 Shot Put 9.23
76 Discus Throw 30.44
77 Discus Throw 34.31
78 Discus Throw 27.53
79 Shot Put 11.77
80 Shot Put 10.66
81 Javelin Throw 29.57
82 Javelin Throw 36.45
83 Javelin Throw 27.97
84 Shot Put 8.08
85 Shot Put 6.71
86 Javelin Throw 50.98
87 Shot Put 9.73
88 Shot Put 14.07
89 Shot Put 11.7
90 Discus Throw 32.01
91 Discus Throw 47.69
92 Discus Throw 31.62
93 Discus Throw 31.98
94 Discus Throw 39.61
95 Discus Throw 29.57
96 Discus Throw 31.37
97 Shot Put 14.88
98 Shot Put 14.01
99 Shot Put 12.74
100 Shot Put 17.57
101 Shot Put 11.77
102 Shot Put 15.72
103 Javelin Throw 36.27
104 Javelin Throw 38.23
105 Javelin Throw 37.56
106 Discus Throw 38.58
107 Discus Throw 47.59
108 Discus Throw 53.4
109 Javelin Throw 56.69
110 Javelin Throw 48.52
111 Javelin Throw 60.85
112 Shot Put 8.85
113 Discus Throw 25.97
114 Shot Put 13.0
115 Shot Put 9.49
116 Discus Throw 30.81
117 Discus Throw 38.65
118 Discus Throw 26.02
119 Discus Throw 42.23
120 Discus Throw 29.47
121 Shot Put 12.46
122 Shot Put 11.78
123 Javelin Throw 26.62
124 Javelin Throw 43.14
125 Shot Put 7.68
126 Discus Throw 19.43
127 Javelin Throw 21.82
128 Javelin Throw 16.59
129 Shot Put 9.75
130 Discus Throw 34.73
131 Javelin Throw 31.2
132 Javelin Throw 39.06
133 Javelin Throw 54.8
134 Javelin Throw 46.34
135 Shot Put 10.39
136 Shot Put 7.22
137 Shot Put 8.34
138 Shot Put 14.24
139 Shot Put 13.1
140 Shot Put 12.04
141 Discus Throw 40.44
142 Discus Throw 42.62
143 Discus Throw 48.04
144 Discus Throw 20.23
145 Discus Throw 27.27
146 Discus Throw 28.42
147 Discus Throw 40.33
148 Discus Throw 46.23
149 Discus Throw 35.58
150 Shot Put 10.83
151 Shot Put 16.4
152 Shot Put 9.97
153 Shot Put 13.91
154 Shot Put 13.49
155 Shot Put 14.39
156 Javelin Throw 34.92
157 Javelin Throw 30.0
158 Javelin Throw 32.62
159 Discus Throw 26.12
160 Discus Throw 32.66
161 Discus Throw 33.12
162 Javelin Throw 33.61
163 Javelin Throw 25.29
164 Javelin Throw 25.16
165 Javelin Throw 45.52
166 Javelin Throw 41.16
167 Javelin Throw 48.85
168 Shot Put 6.92
169 Shot Put 6.57
170 Shot Put 6.83
171 Javelin Throw 23.06
172 Javelin Throw 21.47
173 Discus Throw 18.41
174 Discus Throw 23.89
175 Javelin Throw 17.74
176 Javelin Throw 20.08
177 Javelin Throw 19.39
178 Shot Put 8.23
179 Shot Put 6.82
180 Shot Put 8.3
181 Javelin Throw 47.48
182 Discus Throw 28.76
183 Shot Put 13.35
184 Shot Put 10.66
185 Discus Throw 32.98
186 Javelin Throw 35.78
187 Javelin Throw 25.79
188 Javelin Throw 20.18
189 Javelin Throw 28.51
190 Discus Throw 19.19
191 Discus Throw 17.49
192 Discus Throw 20.59
193 Shot Put 9.93
194 Shot Put 10.89
195 Shot Put 10.11
196 Javelin Throw 28.04
197 Javelin Throw 25.36
198 Javelin Throw 25.69
199 Discus Throw 26.73
200 Discus Throw 27.64
201 Discus Throw 23.43
202 Shot Put 7.17
203 Shot Put 7.41
204 Shot Put 9.36
205 Shot Put 10.14
206 Shot Put 13.13
207 Shot Put 12.27
208 Javelin Throw 37.53
209 Shot Put 7.58
210 Javelin Throw 20.92
211 Javelin Throw 28.63
212 Shot Put 6.97
213 Shot Put 7.0
214 Shot Put 6.79
215 Shot Put 6.5
216 Shot Put 6.82
217 Javelin Throw 36.72
218 Shot Put 7.93
219 Shot Put 6.42
220 Discus Throw 19.12
221 Discus Throw 16.94
222 Discus Throw 20.17
223 Shot Put 10.38
224 Shot Put 11.22
225 Shot Put 14.88
226 Discus Throw 41.2
227 Discus Throw 30.22
228 Discus Throw 34.94
229 Javelin Throw 25.79
230 Shot Put 11.55
231 Shot Put 6.5
232 Shot Put 7.06
233 Javelin Throw 22.57
234 Javelin Throw 30.19
235 Javelin Throw 29.32
236 Discus Throw 17.87
237 Discus Throw 16.23
238 Discus Throw 19.37
239 Shot Put 11.52
240 Shot Put 7.71
241 Shot Put 11.35
242 Javelin Throw 18.8
243 Javelin Throw 27.9
244 Javelin Throw 17.61
245 Discus Throw 24.63
246 Discus Throw 29.68
247 Discus Throw 22.19
248 Shot Put 7.94
249 Shot Put 9.66
250 Shot Put 8.07
251 Javelin Throw 19.1
252 Shot Put 8.95
253 Discus Throw 42.32
254 Shot Put 12.23
255 Shot Put 10.23
256 Javelin Throw 22.68
257 Javelin Throw 49.04
258 Shot Put 10.3
259 Shot Put 9.41
260 Discus Throw 32.42
261 Javelin Throw 19.98
262 Javelin Throw 20.77
263 Javelin Throw 40.04
264 Shot Put 40.04
265 Discus Throw 31.6
266 Shot Put 9.07
267 Javelin Throw 9.07
268 Discus Throw 23.95
269 Javelin Throw 27.14
270 Discus Throw 26.06
271 Shot Put 26.06
272 Discus Throw 25.17
273 Javelin Throw 40.75
274 Javelin Throw 20.76
275 Shot Put 5.76
276 Shot Put 5.76
277 Shot Put 5.76
278 Shot Put 5.64
279 Javelin Throw 34.16
280 Javelin Throw 57.8
281 Discus Throw 40.14
282 Shot Put 9.69
283 Javelin Throw 9.69
284 Discus Throw 15.79
285 Discus Throw 23.97
286 Shot Put 8.0
287 Javelin Throw 8.0
288 Discus Throw 22.28
289 Javelin Throw 22.28
290 Shot Put 22.28
291 Discus Throw 22.32
292 Javelin Throw 25.51
293 Shot Put 6.29
294 Shot Put 6.29
295 Discus Throw 6.29
296 Javelin Throw 38.09
297 Javelin Throw 20.21
298 Shot Put 6.21
299 Discus Throw 19.45
300 Discus Throw 28.08
301 Javelin Throw 26.91
302 Shot Put 26.91
303 Javelin Throw 26.91
304 Discus Throw 33.72
305 Shot Put 11.23
306 Discus Throw 21.58
307 Shot Put 7.09
308 Javelin Throw 32.31
309 Discus Throw 45.56
310 Shot Put 12.58
311 Javelin Throw 51.54
312 Javelin Throw 27.58
313 Shot Put 7.72
314 Discus Throw 22.27
315 Javelin Throw 47.23
316 Discus Throw 43.66
317 Shot Put 10.58
318 Javelin Throw 30.35
319 Javelin Throw 18.86
320 Discus Throw 28.79
321 Shot Put 8.86
322 Javelin Throw 28.47
323 Shot Put 7.66
324 Javelin Throw 51.21
325 Discus Throw 38.36
326 Shot Put 11.93
327 Shot Put 9.12
328 Shot Put 2.1
329 Shot Put 3.79
330 Shot Put 3.4
331 Shot Put 3.83
332 Shot Put 2.68
333 Shot Put 3.52
334 Shot Put 2.51
335 Shot Put 2.15
336 Shot Put 2.73
337 Shot Put 2.84
338 Shot Put 2.91
339 Shot Put 3.76
340 Shot Put 2.47
341 Shot Put 3.58
342 Shot Put 2.78
343 Shot Put 2.79
344 Shot Put 5.08
345 Shot Put 8.2
346 Shot Put 4.74
347 Javelin Throw 24.08
348 Shot Put 4.07
349 Shot Put 3.18
350 Shot Put 4.51
351 Shot Put 3.61
352 Shot Put 4.14
353 Shot Put 4.41
354 Shot Put 4.19
355 Shot Put 3.39
356 Shot Put 4.72
357 Shot Put 4.73
358 Shot Put 4.06
359 Shot Put 4.83
360 Shot Put 3.67
361 Shot Put 4.87
362 Shot Put 3.73
363 Shot Put 3.73
364 Shot Put 3.73
365 Shot Put 5.56
366 Shot Put 3.15
367 Shot Put 3.81
368 Shot Put 3.9
369 Shot Put 4.54
370 Javelin Throw 7.57
371 Shot Put 4.76
372 Javelin Throw 10.68
373 Javelin Throw 8.27
374 Javelin Throw 10.1
375 Shot Put 5.19
376 Shot Put 4.91
377 Shot Put 4.38
378 Javelin Throw 11.49
379 Shot Put 3.6
380 Javelin Throw 7.26
381 Javelin Throw 8.53
382 Shot Put 4.36
383 Shot Put 7.89
384 Shot Put 2.45
385 Javelin Throw 10.5
386 Shot Put 4.38
387 Shot Put 5.07
388 Shot Put 3.36
389 Shot Put 4.92
390 Shot Put 4.75
391 Shot Put 5.35
392 Shot Put 5.03
393 Shot Put 4.52
394 Javelin Throw 20.34
395 Javelin Throw 10.99
396 Shot Put 7.97
397 Shot Put 7.43
398 Javelin Throw 10.87
399 Shot Put 4.56
400 Shot Put 5.6
401 Shot Put 4.05
402 Shot Put 4.42
403 Shot Put 4.31
404 Shot Put 5.44
405 Shot Put 6.23
406 Shot Put 6.24
407 Shot Put 6.05
408 Shot Put 5.06
409 Shot Put 5.49
410 Shot Put 4.41
411 Shot Put 6.66
412 Shot Put 6.5
413 Shot Put 7.31
414 Shot Put 5.24
415 Shot Put 3.73
416 Javelin Throw 19.52
417 Shot Put 4.18
418 Shot Put 4.28
419 Shot Put 5.43
420 Shot Put 7.17
421 Shot Put 4.87
422 Shot Put 7.42
423 Javelin Throw 11.82
424 Javelin Throw 11.16
425 Shot Put 9.79
426 Javelin Throw 8.12
427 Javelin Throw 17.7
428 Javelin Throw 19.78
429 Javelin Throw 9.25
430 Javelin Throw 8.95
431 Javelin Throw 14.62
432 Javelin Throw 10.97
433 Shot Put 6.63
434 Javelin Throw 20.18
435 Shot Put 4.76
436 Javelin Throw 6.55
437 Javelin Throw 13.0
438 Shot Put 7.13
439 Javelin Throw 17.88
440 Shot Put 6.61
441 Javelin Throw 7.22
442 Javelin Throw 12.39
443 Javelin Throw 7.16
444 Javelin Throw 19.74
445 Javelin Throw 24.64
446 Javelin Throw 23.12
447 Javelin Throw 14.67
448 Javelin Throw 15.02
449 Javelin Throw 10.43
450 Javelin Throw 23.12
451 Javelin Throw 15.58
452 Javelin Throw 15.75
453 Javelin Throw 13.85
454 Javelin Throw 9.65
455 Shot Put 2.87
456 Shot Put 7.35
457 Shot Put 9.31
458 Javelin Throw 15.25
459 Javelin Throw 8.1
460 Javelin Throw 23.28
461 Javelin Throw 13.88
462 Javelin Throw 15.39
463 Javelin Throw 13.17
464 Javelin Throw 8.55
465 Javelin Throw 12.32
466 Javelin Throw 24.39
467 Javelin Throw 16.95
468 Javelin Throw 13.58
469 Javelin Throw 13.56
470 Javelin Throw 12.78
471 Shot Put 6.25
472 Javelin Throw 12.83
473 Javelin Throw 12.5
474 Javelin Throw 14.35
475 Javelin Throw 15.98
476 Shot Put 4.5
477 Shot Put 3.63
478 Shot Put 4.61
479 Javelin Throw 14.23
480 Shot Put 3.67
481 Shot Put 5.8
482 Shot Put 6.18
483 Shot Put 2.92
484 Shot Put 4.52
485 Shot Put 3.78
486 Shot Put 4.07
487 Javelin Throw 12.77
488 Shot Put 5.28
489 Javelin Throw 13.61
490 Javelin Throw 9.77
491 Javelin Throw 11.67
492 Shot Put 3.8
493 Shot Put 4.51
494 Shot Put 3.35
495 Shot Put 4.16
496 Javelin Throw 16.59
497 Javelin Throw 13.1
498 Javelin Throw 9.43
499 Javelin Throw 5.85
500 Javelin Throw 17.9
501 Javelin Throw 9.32
502 Javelin Throw 8.78
503 Javelin Throw 13.55
504 Javelin Throw 6.11
505 Javelin Throw 9.38
506 Javelin Throw 7.35
507 Javelin Throw 13.56
508 Javelin Throw 8.69
509 Javelin Throw 14.84
510 Shot Put 9.98
511 Shot Put 8.18
512 Javelin Throw 7.33
513 Javelin Throw 11.95
514 Javelin Throw 9.62
515 Shot Put 6.98
516 Shot Put 7.8
517 Javelin Throw 13.87
518 Javelin Throw 11.3
519 Javelin Throw 9.21
520 Javelin Throw 10.0
521 Javelin Throw 11.5
522 Javelin Throw 11.77
523 Javelin Throw 13.12
524 Javelin Throw 11.79
525 Javelin Throw 13.67
526 Shot Put 10.7
527 Javelin Throw 10.52
528 Javelin Throw 19.36
529 Javelin Throw 18.55
530 Shot Put 5.85
531 Javelin Throw 9.48
532 Javelin Throw 12.28
533 Javelin Throw 18.08
534 Javelin Throw 18.55
535 Shot Put 8.3
536 Javelin Throw 21.87
537 Shot Put 5.56
538 Javelin Throw 11.57
539 Javelin Throw 15.81
540 Javelin Throw 12.08
541 Javelin Throw 10.68
542 Shot Put 7.64
543 Shot Put 7.65
544 Shot Put 5.7
545 Shot Put 7.87
546 Shot Put 7.1
547 Shot Put 7.23
548 Shot Put 8.27
549 Shot Put 6.57
550 Shot Put 7.0
551 Javelin Throw 13.78
552 Javelin Throw 13.04
553 Javelin Throw 10.84
554 Javelin Throw 8.51
555 Javelin Throw 8.13
556 Javelin Throw 16.64
557 Javelin Throw 8.55
558 Javelin Throw 10.22
559 Javelin Throw 11.29
560 Javelin Throw 15.07
561 Shot Put 6.56
562 Javelin Throw 14.17
563 Javelin Throw 6.18
564 Javelin Throw 8.08
565 Javelin Throw 9.05
566 Javelin Throw 8.1
567 Javelin Throw 10.25
568 Javelin Throw 20.13
569 Javelin Throw 20.27
570 Javelin Throw 15.1
571 Javelin Throw 29.38
572 Javelin Throw 11.59
573 Javelin Throw 20.04
574 Javelin Throw 13.56
575 Discus Throw 23.53
576 Javelin Throw 18.5
577 Javelin Throw 10.21
578 Shot Put 4.75
579 Javelin Throw 10.64
580 Javelin Throw 12.08
581 Javelin Throw 9.86
582 Javelin Throw 8.7
583 Javelin Throw 8.02
584 Javelin Throw 7.38
585 Javelin Throw 8.52
586 Javelin Throw 4.71
587 Javelin Throw 5.46
588 Javelin Throw 7.71
589 Javelin Throw 8.63
590 Shot Put 6.7
591 Shot Put 5.87
592 Shot Put 8.94
593 Shot Put 8.91
594 Javelin Throw 15.62
595 Javelin Throw 16.25
596 Javelin Throw 10.57
597 Javelin Throw 11.83
598 Javelin Throw 19.6
599 Javelin Throw 8.48
600 Javelin Throw 11.63
601 Javelin Throw 7.97
602 Javelin Throw 17.1
603 Javelin Throw 20.51
604 Javelin Throw 18.5
605 Javelin Throw 14.33
606 Javelin Throw 10.92
607 Javelin Throw 10.41
608 Javelin Throw 15.71
609 Javelin Throw 11.13
610 Javelin Throw 10.78
611 Javelin Throw 14.37
612 Javelin Throw 11.96
613 Javelin Throw 13.05
614 Javelin Throw 11.12
615 Javelin Throw 6.6
616 Javelin Throw 4.5
617 Javelin Throw 5.86
618 Javelin Throw 10.3
619 Javelin Throw 10.54
620 Javelin Throw 24.79
621 Javelin Throw 18.9
622 Javelin Throw 24.11
623 Javelin Throw 11.64
624 Javelin Throw 19.39
625 Javelin Throw 13.52
626 Javelin Throw 6.74
627 Javelin Throw 9.79
628 Javelin Throw 7.48
629 Javelin Throw 6.43
630 Javelin Throw 6.31
631 Javelin Throw 9.29
632 Javelin Throw 5.44
633 Javelin Throw 9.88
634 Javelin Throw 14.5
635 Javelin Throw 5.64
636 Javelin Throw 8.13
637 Javelin Throw 6.0
638 Javelin Throw 8.19
639 Javelin Throw 10.01
640 Javelin Throw 7.67
641 Javelin Throw 17.73
642 Javelin Throw 6.01
643 Javelin Throw 8.08
644 Javelin Throw 4.86
645 Javelin Throw 4.48
646 Shot Put 5.97
647 Shot Put 7.34
648 Javelin Throw 6.43
649 Javelin Throw 17.51
650 Javelin Throw 11.63
651 Shot Put 10.37
652 Javelin Throw 13.68
653 Shot Put 10.13
654 Shot Put 5.23
655 Javelin Throw 13.49
656 Discus Throw 17.63
657 Shot Put 6.54
658 Shot Put 7.02
659 Discus Throw 12.86
660 Shot Put 5.99
661 Javelin Throw 11.68
662 Javelin Throw 9.42
663 Javelin Throw 11.05
664 Discus Throw 11.96
665 Shot Put 3.76
666 Discus Throw 15.4
667 Discus Throw 8.8
668 Shot Put 5.1
669 Shot Put 6.9
670 Shot Put 7.76
671 Javelin Throw 8.2
672 Shot Put 7.34
673 Shot Put 7.34
674 Shot Put 8.17
675 Shot Put 6.37
676 Shot Put 7.48
677 Javelin Throw 11.72
678 Shot Put 5.56
679 Javelin Throw 9.37
680 Javelin Throw 13.08
681 Javelin Throw 12.03
682 Javelin Throw 18.01
683 Javelin Throw 23.27
684 Shot Put 5.16
685 Shot Put 5.58
686 Discus Throw 11.82
687 Shot Put 5.79
688 Javelin Throw 5.06
689 Javelin Throw 17.08
690 Javelin Throw 14.46
691 Javelin Throw 9.72
692 Shot Put 5.79
693 Javelin Throw 13.36
694 Javelin Throw 10.65
695 Javelin Throw 23.54
696 Javelin Throw 8.79
697 Discus Throw 14.21
698 Discus Throw 12.48
699 Discus Throw 10.01
700 Shot Put 5.7
701 Shot Put 3.78
702 Javelin Throw 16.4
703 Shot Put 3.07
704 Shot Put 5.52
705 Discus Throw 14.15
706 Shot Put 3.22
707 Shot Put 3.44
708 Discus Throw 16.07
709 Discus Throw 12.71
710 Discus Throw 11.55
711 Discus Throw 13.41
712 Shot Put 6.03
713 Shot Put 5.69
714 Discus Throw 16.91
715 Discus Throw 19.04
716 Shot Put 6.38
717 Shot Put 6.76
718 Shot Put 4.88
719 Shot Put 5.33
720 Discus Throw 12.54
721 Shot Put 5.64
722 Discus Throw 8.91
723 Discus Throw 5.15
724 Discus Throw 14.14
725 Shot Put 4.19
726 Shot Put 6.59
727 Discus Throw 11.48
728 Discus Throw 10.52
729 Discus Throw 12.97
730 Discus Throw 5.54
731 Javelin Throw 8.79
732 Javelin Throw 7.49
733 Javelin Throw 13.76
734 Discus Throw 19.1
735 Shot Put 6.39
736 Discus Throw 11.06
737 Shot Put 6.52
738 Discus Throw 8.74
739 Discus Throw 13.21
740 Shot Put 5.32
741 Discus Throw 11.78
742 Shot Put 3.33
743 Discus Throw 11.28
744 Discus Throw 12.84
745 Discus Throw 15.58
746 Discus Throw 11.26
747 Discus Throw 14.97
748 Discus Throw 14.97
749 Discus Throw 11.96
750 Discus Throw 7.25
751 Discus Throw 15.7
752 Shot Put 4.46
753 Discus Throw 8.96
754 Discus Throw 13.46
755 Discus Throw 13.05
756 Discus Throw 8.63
757 Shot Put 6.6
758 Shot Put 6.17
759 Discus Throw 11.02
760 Discus Throw 7.55
761 Shot Put 4.41
762 Shot Put 4.84
763 Discus Throw 9.18
764 Discus Throw 8.74
765 Discus Throw 7.5
766 Shot Put 4.75
767 Shot Put 8.01
768 Shot Put 6.07
769 Shot Put 4.28
770 Javelin Throw 11.93
771 Javelin Throw 19.03
772 Discus Throw 11.06
773 Discus Throw 15.78
774 Discus Throw 12.32
775 Discus Throw 12.43
776 Discus Throw 16.05
777 Discus Throw 15.21
778 Discus Throw 16.46
779 Discus Throw 11.18
780 Discus Throw 10.0
781 Discus Throw 13.52
782 Shot Put 7.13
783 Shot Put 8.88
784 Shot Put 5.51
785 Shot Put 6.35
786 Shot Put 7.58
787 Javelin Throw 14.61
788 Javelin Throw 18.09
789 Javelin Throw 23.13
790 Javelin Throw 17.29
791 Javelin Throw 11.89
792 Discus Throw 21.27
793 Discus Throw 16.65
794 Shot Put 4.64
795 Discus Throw 17.28
796 Discus Throw 26.18
797 Discus Throw 16.6
798 Discus Throw 15.64
799 Discus Throw 16.08
800 Discus Throw 23.37
801 Discus Throw 13.9
802 Discus Throw 11.72
803 Shot Put 7.44
804 Javelin Throw 8.29
805 Javelin Throw 6.01
806 Javelin Throw 11.8
807 Javelin Throw 19.46
808 Discus Throw 11.83
809 Discus Throw 14.62
810 Discus Throw 13.19
811 Javelin Throw 24.75
812 Javelin Throw 15.3
813 Javelin Throw 14.55
814 Javelin Throw 18.5
815 Shot Put 6.1
816 Shot Put 6.16
817 Shot Put 5.66
818 Shot Put 11.34
819 Shot Put 6.16
820 Javelin Throw 10.41
821 Javelin Throw 8.13
822 Javelin Throw 8.12
823 Javelin Throw 18.31
824 Javelin Throw 11.95
825 Javelin Throw 22.88
826 Javelin Throw 12.16
827 Javelin Throw 11.58
828 Discus Throw 11.11
829 Discus Throw 16.8
830 Discus Throw 14.14
831 Shot Put 4.67
832 Shot Put 5.42
833 Shot Put 4.95
834 Shot Put 4.79
835 Discus Throw 26.22
836 Discus Throw 16.42
837 Discus Throw 12.62
838 Shot Put 5.61
839 Discus Throw 15.73
840 Javelin Throw 24.65
841 Javelin Throw 18.47
842 Shot Put 6.9
843 Discus Throw 10.69
844 Discus Throw 15.65
845 Discus Throw 16.12
846 Discus Throw 11.53
847 Discus Throw 13.05
848 Discus Throw 13.12
849 Shot Put 5.25
850 Discus Throw 7.97
851 Discus Throw 13.5
852 Shot Put 10.78
853 Javelin Throw 13.64
854 Javelin Throw 11.63
855 Javelin Throw 11.41
856 Javelin Throw 11.42
857 Javelin Throw 19.98
858 Javelin Throw 19.2
859 Javelin Throw 21.17
860 Shot Put 5.9
861 Javelin Throw 8.83
862 Javelin Throw 9.99
863 Javelin Throw 15.14
864 Javelin Throw 11.76
865 Shot Put 4.55
866 Shot Put 7.07
867 Shot Put 8.76
868 Javelin Throw 12.11
869 Javelin Throw 20.87
870 Javelin Throw 17.26
871 Javelin Throw 22.3
872 Shot Put 5.09
873 Shot Put 4.4
874 Shot Put 2.96
875 Shot Put 4.17
876 Shot Put 4.21
877 Shot Put 3.89
878 Shot Put 2.84
879 Shot Put 5.95
880 Shot Put 6.99
881 Shot Put 7.2
882 Javelin Throw 9.5
883 Discus Throw 18.96
884 Shot Put 7.79
885 Discus Throw 14.23
886 Discus Throw 15.39
887 Shot Put 3.06
888 Discus Throw 10.06
889 Shot Put 7.29
890 Discus Throw 12.44
891 Discus Throw 13.82
892 Discus Throw 15.56
893 Discus Throw 10.09
894 Discus Throw 14.23
895 Shot Put 6.88
896 Shot Put 5.53
897 Shot Put 6.7
898 Discus Throw 9.38
899 Shot Put 7.42
900 Discus Throw 9.21
901 Discus Throw 15.72
902 Discus Throw 18.15
903 Discus Throw 7.54
904 Discus Throw 17.04
905 Discus Throw 16.38
906 Discus Throw 8.55
907 Discus Throw 14.08
908 Discus Throw 11.64
909 Javelin Throw 12.28
910 Discus Throw 14.0
911 Javelin Throw 16.4
912 Discus Throw 16.46
913 Discus Throw 17.53
914 Discus Throw 18.15
915 Shot Put 6.95
916 Javelin Throw 20.62
917 Javelin Throw 17.63
918 Shot Put 5.66
919 Discus Throw 20.96
920 Shot Put 5.48
921 Discus Throw 5.48
922 Shot Put 6.29
923 Javelin Throw 30.18
924 Javelin Throw 25.42
925 Javelin Throw 24.12
926 Shot Put 8.81
927 Discus Throw 8.81
928 Shot Put 7.8
929 Discus Throw 7.8
930 Discus Throw 23.76
931 Javelin Throw 24.64
932 Discus Throw 11.24
933 Discus Throw 12.34
934 Discus Throw 21.33
935 Discus Throw 11.93
936 Discus Throw 18.43
937 Discus Throw 12.14
938 Discus Throw 20.0
939 Javelin Throw 13.15
940 Javelin Throw 14.76

In [14]:
df_selected

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,DOB,NATIONALITY,WIND,CATEGORY_EVENT,GENDER,COMPETITION,YEAR,REGION,MAPPED_EVENT,Metric
0,"Chong Bin Mohd Isham, Akid",32.40m,FAC,34,2,Open,Hammer Throw,0,(7.26kg),A512E90,24/11/90,nan,,Throw,Male,54th SA Inter Club Championships 2024,2024,Local,Hammer Throw,32.40
1,"Ng, Joash",1.89m,Team M&J,5,10,U7,Shot Put,0,1kg Medicine,nan,11/1/19,nan,,Throw,Male,11th Club ZOOM Kindred Spirit 2024 & PEERS,2024,Local,Shot Put,1.89
2,"Franz, Alexander",3.43m,Club ZOOM,5,3,U7,Shot Put,0,1kg Medicine,nan,26/4/19,nan,,Throw,Male,11th Club ZOOM Kindred Spirit 2024 & PEERS,2024,Local,Shot Put,3.43
3,"Lee, Tzu Yun",53.18m,Club Zoom,30,1,Open,Discus Throw,0,,nan,24/11/94,nan,,Throw,Male,84th Singapore Open Track & Field,2024,Local,Discus Throw,53.18
4,"YEE WAI TENG, MELISSA",10.60m,SINGAPORE,26,2,Open,Shot Put,0,,nan,8/8/98,nan,,Throw,Female,84th Singapore Open Track & Field,2024,Local,Shot Put,10.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,"Sheik Alau'ddin, Sheik Fayz",9.40m,Republic Polytechnic,0,3,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,9.40
1704,"Tay, Arvin",10.07m,Singapore Management Universit,0,2,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,10.07
1705,"Josiah, Chan",7.03m,Singapore Polytechnic,0,7,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,7.03
1706,"Subba, Sugam",7.17m,Singapore Polytechnic,0,6,Open,Shot Put,0,None,nan,nan,nan,None,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,7.17
1707,Raeshon Loo Wei Ming,12.01,None,None,3,None,Shot Put,None,None,None,31-Jan-01,SGP,None,Throw,Male,Teivashüppe GP Lasnamäe KJH,2025,International,Shot Put,12.01

In [15]:
def length(string):

    B = ''
    year = ''

    try:

        length = len(string)

        if length == 2:

            string = '19' + string

        elif length == 1:

            string = ''

        else:

            pass

        if string is not None or len(string) != 1:

            B = parser.parse(string, dayfirst=True)
                        
    except:

        pass

    return B


df_selected['DOB_new'] = df_selected['DOB'].apply(length)



#B = parser.parse("10-09-2021", dayfirst = True)

In [16]:
type(df_selected['DOB_new'])

pandas.core.series.Series

In [17]:
df_selected['DOB_new'] = pd.to_datetime(df_selected['DOB_new'], errors='coerce')


df_selected['year_extract']=df_selected['DOB_new'].dt.strftime('%Y')
#df_selected['year_extract'] = df_selected['year_extract'].replace(regex=r'20', value='19')

#df_selected['age_extract'].apply(np.sign).replace({-1: 'down', 1: 'up', 0: 'zero'})


df_selected['year_extract'] = pd.to_numeric(df_selected['year_extract'])

In [18]:
df_selected['age_extract'] = 2024 - df_selected['year_extract']

In [19]:
def age(number):  # correct negative age numbers
    
    if number<0:
        
        number+=100
        
    return number


df_selected['age_extract'] = df_selected['age_extract'].apply(age)

In [20]:
df_selected.tail(50)

,NAME,RESULT,TEAM,AGE,COMPETITION_RANK,DIVISION,EVENT,DISTANCE,EVENT_CLASS,UNIQUE_ID,...,CATEGORY_EVENT,GENDER,COMPETITION,YEAR,REGION,MAPPED_EVENT,Metric,DOB_new,year_extract,age_extract
1658,"Low, Jun Jie Jonathan",44.41m,National University Singapore,0,1,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,44.41,NaT,NaN,NaN
1659,"Qin, Yi",25.18m,National University Singapore,0,8,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,25.18,NaT,NaN,NaN
1660,"Chandramohan Meena, Girish",31.03m,Singapore University of Social,0,4,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,31.03,NaT,NaN,NaN
1661,"Sheik Alau'ddin, Sheik Fayz",40.70m,Republic Polytechnic,0,2,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,40.70,NaT,NaN,NaN
1662,"Mook, He Jun",36.50m,Singapore Management Universit,0,3,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,36.50,NaT,NaN,NaN
1663,"Josiah, Chan",26.70m,Singapore Polytechnic,0,6,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,26.70,NaT,NaN,NaN
1664,"Ng, Bryan",23.26m,Singapore Polytechnic,0,10,Open,Discus Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Discus Throw,23.26,NaT,NaN,NaN
1665,"Chan, Cara",7.61m,Ngee Ann Polytechnic,0,3,Open,Shot Put,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Shot Put,7.61,NaT,NaN,NaN
1666,"Phua, Kia Ern, Jaydene",8.07m,National University Singapore,0,2,Open,Shot Put,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Shot Put,8.07,NaT,NaN,NaN
1667,"Wan, Kaixin Clarice",8.63m,National University Singapore,0,1,Open,Shot Put,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Shot Put,8.63,NaT,NaN,NaN
1668,"Tan, Yixi",6.98m,Singapore Polytechnic,0,4,Open,Shot Put,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Shot Put,6.98,NaT,NaN,NaN
1669,"Lee, Shane",27.64m,Temasek Polytechnic,0,9,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,27.64,NaT,NaN,NaN
1670,"Lee, Ryan",FOUL,Temasek Polytechnic,0,0,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,27.64,NaT,NaN,NaN
1671,"Quek, Jeremiah",42.83m,Ngee Ann Polytechnic,0,3,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,42.83,NaT,NaN,NaN
1672,"Lim, Bryan,Chen Rui",FOUL,Nanyang Polytechnic,0,0,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,42.83,NaT,NaN,NaN
1673,"Wong, Zheng Yan",36.79m,Nanyang Polytechnic,0,5,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,36.79,NaT,NaN,NaN
1674,"Muhammad, Ammar",FOUL,Nanyang Technological Universi,0,0,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,36.79,NaT,NaN,NaN
1675,"Kannan, Pavindhiran",FOUL,Nanyang Technological Universi,0,0,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,36.79,NaT,NaN,NaN
1676,"Liu, Yanchen",35.70m,Singapore Institute of Technol,0,6,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,35.70,NaT,NaN,NaN
1677,"Chua, Qi Long",38.67m,National University Singapore,0,4,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,38.67,NaT,NaN,NaN
1678,"Ng Kai Leong, Roy",50.02m,National University Singapore,0,2,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,50.02,NaT,NaN,NaN
1679,"Chandramohan Meena, Girish",57.03m,Singapore University of Social,0,1,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,57.03,NaT,NaN,NaN
1680,"Subba, Sugam",32.47m,Singapore Polytechnic,0,7,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,32.47,NaT,NaN,NaN
1681,"Nasrudin, Saifuddin",30.59m,Singapore Polytechnic,0,8,Open,Javelin Throw,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,30.59,NaT,NaN,NaN
1682,"Tan, Melody",22.43m,Temasek Polytechnic,0,5,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,22.43,NaT,NaN,NaN
1683,"Chan, Cara",23.03m,Ngee Ann Polytechnic,0,2,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,23.03,NaT,NaN,NaN
1684,"Lim, Joey",22.76m,Singapore Institute of Technol,0,4,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,22.76,NaT,NaN,NaN
1685,"Phua, Kia Ern, Jaydene",23.47m,National University Singapore,0,1,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,23.47,NaT,NaN,NaN
1686,"Seah, Michelle Xin Yi",22.96m,Singapore Institute of Managem,0,3,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,22.96,NaT,NaN,NaN
1687,"Tan, Yixi",21.12m,Singapore Polytechnic,0,6,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,21.12,NaT,NaN,NaN
1688,"Yew, Meredith",19.86m,Singapore Polytechnic,0,7,Open,Discus Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Discus Throw,19.86,NaT,NaN,NaN
1689,"Yam, Natalie",16.59m,Temasek Polytechnic,0,6,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,16.59,NaT,NaN,NaN
1690,"Chan, Cara",27.67m,Ngee Ann Polytechnic,0,2,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,27.67,NaT,NaN,NaN
1691,"Lim, Joey",25.30m,Singapore Institute of Technol,0,3,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,25.30,NaT,NaN,NaN
1692,"Seah, Michelle Xin Yi",29.89m,Singapore Institute of Managem,0,1,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,29.89,NaT,NaN,NaN
1693,"Lim, Celeste",20.98m,Republic Polytechnic,0,5,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,20.98,NaT,NaN,NaN
1694,"Ong, Zhi Qi",24.59m,Republic Polytechnic,0,4,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,24.59,NaT,NaN,NaN
1695,"Tan, Yixi",14.67m,Singapore Polytechnic,0,7,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,14.67,NaT,NaN,NaN
1696,"Dione, Fong",13.52m,Singapore Polytechnic,0,8,Open,Javelin Throw,0,None,nan,...,Throw,Female,IVP Track & Field Championships 2025,2025,Local,Javelin Throw,13.52,NaT,NaN,NaN
1697,"Tan, Brandon",5.47m,Temasek Polytechnic,0,9,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,5.47,NaT,NaN,NaN
1698,"Lee, Nicolas",6.81m,Temasek Polytechnic,0,8,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,6.81,NaT,NaN,NaN
1699,"Ameer Arafat, Ameer Abbas",8.52m,Institute of Technical Educati,0,4,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,8.52,NaT,NaN,NaN
1700,"Lim, Bryan,Chen Rui",FOUL,Nanyang Polytechnic,0,0,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,8.52,NaT,NaN,NaN
1701,"Wong, Zheng Yan",8.06m,Nanyang Polytechnic,0,5,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,8.06,NaT,NaN,NaN
1702,"Xiao, Hongyang",10.21m,National University Singapore,0,1,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,10.21,NaT,NaN,NaN
1703,"Sheik Alau'ddin, Sheik Fayz",9.40m,Republic Polytechnic,0,3,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,9.40,NaT,NaN,NaN
1704,"Tay, Arvin",10.07m,Singapore Management Universit,0,2,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,10.07,NaT,NaN,NaN
1705,"Josiah, Chan",7.03m,Singapore Polytechnic,0,7,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,7.03,NaT,NaN,NaN
1706,"Subba, Sugam",7.17m,Singapore Polytechnic,0,6,Open,Shot Put,0,None,nan,...,Throw,Male,IVP Track & Field Championships 2025,2025,Local,Shot Put,7.17,NaT,NaN,NaN
1707,Raeshon Loo Wei Ming,12.01,None,None,3,None,Shot Put,None,None,None,...,Throw,Male,Teivashüppe GP Lasnamäe KJH,2025,International,Shot Put,12.01,2001-01-31,2001.0,23.0

In [21]:
# If NSG event then choose AGE otherwise choose age_extract

condition1=df_selected['COMPETITION']=='National School Games'
#condition2=((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))
#condition3=df['SEED_CONV']<df['RESULT_CONV']
#condition4=~((df['CATEGORY_EVENT']=='Jump')|(df['CATEGORY_EVENT']=='Throw'))


df_selected['age_extract']=df_selected['AGE'].where((condition1), df_selected['age_extract'].values)

In [22]:
os.chdir('/Users/veesheenyuen/Desktop/DataScience/SAA/Throws Program/')


df_selected.to_csv('athletes_throws_mapped.csv', sep=',', encoding='utf-8-sig', index=False)

In [23]:
df_male = df_selected[((df_selected['CATEGORY_EVENT']=='Throw') & (df_selected['GENDER']=='Male'))]

In [26]:
df_male = df_male.rename(columns={'Metric': 'Distance(m)', 'age_extract': 'Age(yrs)'})

In [27]:
fig = px.scatter(df_male, x="Age(yrs)", y="Distance(m)", color='MAPPED_EVENT', symbol ='MAPPED_EVENT', color_discrete_sequence=['red', 'blue', 'yellow', 'green'])
fig.add_hline(y=66.2, line_width=3, line_dash="dash", line_color="green", annotation_text="Javelin Throw Male")
fig.add_hline(y=50.02, line_width=3, line_dash="dash", line_color="yellow", annotation_text="Discus Throw Male")
fig.add_hline(y=17.3, line_width=3, line_dash="dash", line_color="blue", annotation_text="Shot Put Male")
fig.add_hline(y=59.76, line_width=3, line_dash="dash", line_color="red", annotation_text="Hammer Throw Male")


fig.show()

In [2690]:
df_female = df_selected[((df_selected['CATEGORY_EVENT']=='Throw') & (df_selected['GENDER']=='Female'))]

fig = px.scatter(df_female, x="age_extract", y="Metric", color='MAPPED_EVENT', symbol ='MAPPED_EVENT', color_discrete_sequence=['red', 'blue', 'green'])
fig.add_hline(y=40.59, line_width=3, line_dash="dash", line_color="pink", annotation_text="Javelin Female")

fig.show()

In [2691]:
import pandas_gbq
from google.oauth2 import service_account


credentials = service_account.Credentials.from_service_account_file(
    '/Users/veesheenyuen/Desktop/DataScience/Keys/saa-analytics-7c8937b70609.json',
)

sql="""
SELECT YEAR, EVENT, SUB_EVENT, GENDER, NAME, RESULT, RANK, CATEGORY_EVENT, COMPETITION, STAGE, HEAT
FROM `saa-analytics.benchmarks.saa_benchmarks_prod`
WHERE YEAR='2023' AND COMPETITION='Southeast Asian Games' AND (RANK='3' OR RANK='3.0')
"""

SEAG = pandas_gbq.read_gbq(sql, project_id="saa-analytics", credentials=credentials)

Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|

In [2692]:
SEAG

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
0,2023,4 x 100m,None,Male,"{0: '\xa0', 1: ' Jonathan Nyepa, Khairul Hafiz...",39.36,3,Relay,Southeast Asian Games,None,None
1,2023,4 x 400m,None,Male,"{0: '\xa0', 1: ' Muhammad Firdaus Bin Mohamad ...",03:08.8,3,Relay,Southeast Asian Games,None,None
2,2023,4 x 100m,None,Female,"{0: '\xa0', 1: ' Azreen Nabila Alias, Nur Afri...",44.58,3,Relay,Southeast Asian Games,None,None
3,2023,4 x 400m,None,Female,"{0: '\xa0', 1: ' Sukanya Janchaona, Benny Nont...",03:39.3,3,Relay,Southeast Asian Games,None,None
4,2023,400m,None,Male,Frederick Ramirez,46.63,3,Sprint,Southeast Asian Games,None,None
...,...,...,...,...,...,...,...,...,...,...,...
75,2023,100m Hurdles,None,Female,Natchaya Chowpakpang,14.23,3,Hurdles,Southeast Asian Games,Heats,Heat 2
76,2023,Marathon,None,Male,Nguyen Thanh Hoang,2:35:49,3.0,Marathon,Southeast Asian Games,None,None
77,2023,Marathon,None,Female,Christine Organiza Hallasgo,2:50:27,3.0,Marathon,Southeast Asian Games,None,None
78,2023,20km Race Walk,None,Female,Kotchaphon Tangsrivong,1:57:11,3.0,20km Race Walk,Southeast Asian Games,None,None
79,2023,20km Race Walk,None,Male,Pyae Phyo Htun,1:49:39,3.0,20km Race Walk,Southeast Asian Games,None,None

In [2693]:
benchmarks = SEAG[SEAG['CATEGORY_EVENT']=='Throw']

In [2694]:
benchmarks

,YEAR,EVENT,SUB_EVENT,GENDER,NAME,RESULT,RANK,CATEGORY_EVENT,COMPETITION,STAGE,HEAT
10,2023,Shot Put,None,Male,Muhammad Ziyad Zolkefli,17.3,3,Throw,Southeast Asian Games,None,None
20,2023,Discus Throw,None,Male,Bandit Singhatongkul,50.02,3,Throw,Southeast Asian Games,None,None
21,2023,Javelin Throw,None,Male,Agustinus Abadi Ndiken,66.2,3,Throw,Southeast Asian Games,None,None
27,2023,Discus Throw,None,Female,Le Thi Cam Dung,45.08,3,Throw,Southeast Asian Games,None,None
35,2023,Shot Put,Multievents,Female,Norliana Kamaruddin,10.59,3,Throw,Southeast Asian Games,None,None
36,2023,Javelin Throw,Multievents,Female,Nguyen Linh Na,40.59,3,Throw,Southeast Asian Games,None,None
43,2023,Hammer Throw,None,Male,Sadat Marzuki Ajisan,59.76,3,Throw,Southeast Asian Games,None,None
49,2023,Shot Put,None,Female,Nani Shahirah Maryata,14.44,3,Throw,Southeast Asian Games,None,None
50,2023,Hammer Throw,None,Female,Nurul Hidayah Lukman,49.61,3,Throw,Southeast Asian Games,None,None
51,2023,Javelin Throw,None,Female,Evalyn Palabrica,48.31,3,Throw,Southeast Asian Games,None,None
54,2023,Shot Put,Multievents,Male,Janry Ubas,10.95,3,Throw,Southeast Asian Games,None,None
55,2023,Discus Throw,Multievents,Male,Janry Ubas,32.35,3,Throw,Southeast Asian Games,None,None
56,2023,Javelin Throw,Multievents,Male,Janry Ubas,48.56,3,Throw,Southeast Asian Games,None,None

In [2695]:
# Create a line chart using Plotly graph objects
fig = go.Figure()

# Variable 1
fig.add_trace(go.Scatter(
    x=df_selected['age_extract'],  # x-axis
    y=df_selected['Metric'],  # y-axis
    mode='lines+markers',  # Connect data points with lines and add markers
    name='Line1',  # Name in the legend

    marker=dict(
        symbol='square',    # Change the marker symbol to a circle
        size=10,            # Set the marker size
        color='red'),       # Set the marker color

    line=dict(
        color='blue',        # Change the line color to red
        width=5)             # Set the line width
))